"""v3 added foreign keys related to board

Revision ID: 01ffcfb4ff5c
Revises: 8a48d669d31f
Create Date: 2022-08-13 19:27:54.166308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ffcfb4ff5c'
down_revision = '8a48d669d31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('plant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'board', 'plant', ['plant_id'], ['id'])
    op.add_column('sensor_readings', sa.Column('board_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sensor_readings', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_readings', type_='foreignkey')
    op.drop_column('sensor_readings', 'board_id')
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'plant_id')
    # ### end Alembic commands ###
