"""v7 added image to plant

Revision ID: 077633bce07e
Revises: 9d473e45f5c6
Create Date: 2022-08-14 18:09:22.787714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077633bce07e'
down_revision = '9d473e45f5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'image')
    # ### end Alembic commands ###
