"""v4 added foreign keys related to pump state

Revision ID: 514038ed2873
Revises: 53859400f9b3
Create Date: 2022-08-13 20:07:13.115063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514038ed2873'
down_revision = '53859400f9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pump_state_history', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pump_state_history', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pump_state_history', type_='foreignkey')
    op.drop_column('pump_state_history', 'board_id')
    # ### end Alembic commands ###
