"""v3 added foreign keys related to board

Revision ID: 53859400f9b3
Revises: 7c496925078f
Create Date: 2022-08-13 20:04:11.501029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53859400f9b3'
down_revision = '7c496925078f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('plant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board', 'plant', ['plant_id'], ['id'])
    op.add_column('sensor_readings', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sensor_readings', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_readings', type_='foreignkey')
    op.drop_column('sensor_readings', 'board_id')
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'plant_id')
    # ### end Alembic commands ###
