"""v1 added a new table board and foreign keys to thate

Revision ID: 8a48d669d31f
Revises: c4a188efd26e
Create Date: 2022-08-13 19:07:01.086407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a48d669d31f'
down_revision = 'c4a188efd26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'board_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
