"""v7 added image to plant

Revision ID: 9d473e45f5c6
Revises: c704890e9dc6
Create Date: 2022-08-14 18:09:01.295476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d473e45f5c6'
down_revision = 'c704890e9dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'image')
    # ### end Alembic commands ###
