"""v1 added an extra field for board_id in sensorReading table

Revision ID: c4a188efd26e
Revises: 
Create Date: 2022-08-13 17:03:02.740909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a188efd26e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('board_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'board_id')
    # ### end Alembic commands ###
