"""v6 added status to board

Revision ID: c704890e9dc6
Revises: 514038ed2873
Create Date: 2022-08-14 00:02:57.900160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c704890e9dc6'
down_revision = '514038ed2873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'status')
    # ### end Alembic commands ###
